# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Surbey
vocation: Cloud Solutions Architect
email: msurbey@redhat.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog! Here you can find tips, tricks, and how-to's
  for the monern-day IT professional and polymath.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ecwpz91.github.io/" # the base hostname & protocol for your site
twitter_username: ecwpz91
github_username:  ecwpz91

# Build settings
markdown: kramdown

# Exclude files
exclude:
  - fonts
  - grunt
  - js
  - less
  - node_modules
  - script
  - vendor
  - _mdwriter.cson
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - package.json
  - README.md

# Enable gems
gems:
  - jemoji

# Local server port
port: 4000

# Local server hostname
host: 0.0.0.0
