title: Mike Surbey's Home Page
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog. Here you can find tips, tricks, and how-to's
  on topics I see as noteworthy. Enjoy!
baseurl:
url:
pinboard_username: msurbey
twitter_username: ecwpz91
github_username: ecwpz91
markdown: kramdown
exclude:
  - fonts
  - grunt
  - js
  - less
  - node_modules
  - script
  - vendor
  - _mdwriter.cson
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - package.json
  - README.md
plugins_dir:
  - jemoji
port: 4000
host: 0.0.0.0
